In [3]:
i = 1+2
print (i)

3


In [6]:
type('asd')

str

In [8]:
type(i)

int

In [9]:
text = 'Jon'
print(type(text))

<class 'str'>


In [1]:
a = "123"
b = 456
c = a + b
print(c)

TypeError: can only concatenate str (not "int") to str

In [7]:
line1=1
print('line 1 done')
try:
    line2=a-2
    print('line 2 done')
    line3=3
    print('line 3 done')
    line4=4
    print('line 4 done')
except:
    line5=5
    print('line 5 done')

line6=6
print('line 6 done')


line 1 done
line 5 done
line 6 done


In [7]:
lst = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight']

for i, val in enumerate(lst):
    print(i, val)

0 one
1 two
2 three
3 four
4 five
5 six
6 seven
7 eight


In [1]:
x=0
while(x<2):
    print(x)
    x=x+1 

0
1


In [2]:
x="Go"

if(x=="Go"):

  print('Go ')

else:

  print('Stop')

print('Mike')

Go 
Mike


In [3]:
class Points(object):
  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p1=Points("A","B")
p1.print_point()

x= A  y= B


In [4]:
class Points(object):

  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p2=Points(1,2)

p2.x='A'

p2.print_point()

x= A  y= 2


In [1]:
import numpy as np

In [3]:
X = np.array([1,2,3])
print(X)

[1 2 3]


In [5]:
X = np.array([[1,2,3] , [2,3,4] , [3,4,5]])
print(X)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [11]:
X = np.array([[1,0] , [0,1]])
print('A=',X)
Y = np.array([[2,1] , [1,2]])
print('B=',Y)

A= [[1 0]
 [0 1]]
B= [[2 1]
 [1 2]]


In [13]:
Z = X*Y
Z

array([[2, 0],
       [0, 2]])

In [14]:
X+Y

array([[3, 1],
       [1, 3]])

In [16]:
A = np.array([[0,1,1],[1,0,1]])
B = np.array([[1,1],[1,1],[-1,1]])

print('A = \n',A)
print('B = \n',B)

A = 
 [[0 1 1]
 [1 0 1]]
B = 
 [[ 1  1]
 [ 1  1]
 [-1  1]]


In [19]:
np.dot(A,B)

array([[0, 2],
       [0, 2]])

In [20]:
B.size

6

In [21]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [23]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [24]:

X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [26]:

X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [27]:
with open("Example1.txt","w") as File1:

    File1.write('This is line 1 \nThis is line 2 \nThis is line 3')

In [28]:
with open("Example1.txt","r") as File1:

    file_stuff=File1.readline ()

    print(file_stuff)

This is line 1 



In [4]:
import requests

url = 'http://www.ibm.com/'
r = requests.get(url)

In [5]:
r.status_code

200

In [13]:
r.request.headers

{'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': '_abck=FDE3EEF23FF8E3B2065CA6F109D69E5C~-1~YAAQPSEPF5dWo6+HAQAASPnJ4Al/FdwtJF4vygsvQjP57lo87oETSoMIwC34N+3g9Hsmn3vdvA+hTA3X0Bk9Eg+05nlxj/PFF0NnQ7wmEL99F/32LdC1/jfcFRVgfNHLC0aj0Z5upAcqUNMDaYmOGztW/vdquYbVfJT0qbedjIm89tk6bEVmPfr5NixG8tDYgOyJH7BpHB8TnsbAwMexbPsNOJ6t1/lujppLkeqP4vDDlHJlUFKyOF9ZjoOq/I1HU1o+POULBsSjQlX6A5qY/sM5DHrB9PwkSDlO5FD0Ycl8tcHwbIpTLSc+v8d1w9Q7yu/WUfMA5YoGw3MJyvt6scM=~-1~-1~-1; bm_sz=E9CBC222CA2055F247D51866D6F23E56~YAAQPSEPF5hWo6+HAQAASPnJ4BNeDQ+0L9MQWphdgl7psEy0hLJXyaQH92MO2iNobRhRYPyM5n++oUd9Rgib61aLZ94mDMozTYMDuetS1stFxeiHrKXhYGX32GwfFbc0x4VVxeo5wvUA3yNhH7jhr1L2dxXY1YWJvA/8uOQSLY8Lc3GkDpfftxCpoOUk1pPbTiKoYbzX3Cg5mLlR+tta8mVSDfmvby5cN+K21zYBEVJt6vvxNGH2/Bb9agjZY7CEWn0fca+roy9vG/nge/1Gf004OOrVGHitYCVWkqvmdFw=~4469816~3356464'}

In [14]:
type(r)

requests.models.Response

In [15]:
print(r.request.body)

None


In [16]:
header = r.headers
header

{'Server': 'Apache', 'x-drupal-dynamic-cache': 'UNCACHEABLE', 'x-ua-compatible': 'IE=edge', 'Content-Language': 'en-in', 'x-generator': 'Drupal 9 (https://www.drupal.org)', 'Link': '<//1.cms.s81c.com>; rel=preconnect; crossorigin, <//1.cms.s81c.com>; rel=dns-prefetch', 'x-dns-prefetch-control': 'on', 'x-drupal-cache': 'MISS', 'Last-Modified': 'Tue, 02 May 2023 15:25:25 GMT', 'ETag': '"1683041125"', 'Content-Type': 'text/html; charset=UTF-8', 'x-acquia-host': 'www.ibm.com', 'x-acquia-path': '/in-en', 'x-acquia-site': '', 'x-acquia-purge-tags': '', 'x-varnish': '221217355 217494152', 'x-cache-hits': '2', 'x-age': '2343', 'Accept-Ranges': 'bytes', 'Cache-Control': 'public, max-age=300', 'Expires': 'Wed, 03 May 2023 08:50:46 GMT', 'X-Akamai-Transformed': '9 11409 0 pmb=mTOE,2', 'Content-Encoding': 'gzip', 'Date': 'Wed, 03 May 2023 08:45:46 GMT', 'Content-Length': '11582', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'x-content-type-options': 'nosniff', 'X-XSS-Protection': '1; mod

In [17]:
type(header)

requests.structures.CaseInsensitiveDict

In [18]:
header['date']

'Wed, 03 May 2023 08:45:46 GMT'

In [19]:
header['Content-Type']

'text/html; charset=UTF-8'

In [20]:
r.encoding

'UTF-8'

In [21]:
r.text[:100]

'<!DOCTYPE html>\n<html lang="en-in" dir="ltr">\n  <head>\n    <meta charset="utf-8" />\n<script>digitalD'

In [113]:
import requests
from bs4 import BeautifulSoup
import pandas as pd


page = requests.get('http://quotes.toscrape.com/').text

# Create a BeautifulSoup object
soup = BeautifulSoup(page, 'html.parser')

#Lets find all <div> tag
# soup = soup.body
# print(soup.span.text.split('\n')[0])

# soup.find_all(string='Albert Einstein')

# print(soup.find_all("div",class_="quote"))

# for i, x in enumerate(soup.find_all('div', class_ = 'quote')):
#     print(i, ' ---> ', x)
#     print()

# list_of_div = soup.find_all(name = 'div')
# print(len(list_of_div))


# for x in (quotes_bs.find_all('div', class_ = 'quote')):
#     print(x.span.string)
#     print('From', x.find_all('small')[0].string)
#     print()


quote_df = pd.DataFrame({}, columns=[0,1])

for x in soup.find_all('div', class_='quote'):
    q = x.find_all('span')[0].string
    a = x.find_all('small')[0].string

quote_df

0    1
0                                    Albert Einstein  NaN
1  “The world as we have created it is a process ...  NaN
0                                       J.K. Rowling  NaN
1  “It is our choices, Harry, that show what we t...  NaN
0                                    Albert Einstein  NaN
1  “There are only two ways to live your life. On...  NaN
0                                        Jane Austen  NaN
1  “The person, be it gentleman or lady, who has ...  NaN
0                                     Marilyn Monroe  NaN
1  “Imperfection is beauty, madness is genius and...  NaN
0                                    Albert Einstein  NaN
1  “Try not to become a man of success. Rather be...  NaN
0                                         André Gide  NaN
1  “It is better to be hated for what you are tha...  NaN
0                                   Thomas A. Edison  NaN
1  “I have not failed. I've just found 10,000 way...  NaN
0                                  Eleanor Roosevelt  NaN
1  “A woman is like a tea bag; you never know how...  NaN
0                                       Steve Martin  NaN
1  “A day without sunshine is like, you know, nig...  NaN

In [98]:
import pandas as pd

# DataFrames
df1 = pd.DataFrame(columns=list('AB'))
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'))

print(df1)
print(df2)
print(pd.concat([df1, df2]))




Empty DataFrame
Columns: [A, B]
Index: []
   A  B
0  5  6
1  7  8
   A  B
0  5  6
1  7  8


['A', 'B']

In [105]:
['Author', 'Quote']

['Author', 'Quote']

In [116]:
A=['1','2','3'] 
for a in A: print(2*a) 

11
22
33


In [129]:
for i in range(1,5): 
    if (i!=1): 
        print(i)

2
3
4


In [131]:
a=np.array([10,9,8,7,6]) 
a+1

array([11, 10,  9,  8,  7])

In [1]:
str = 'this is a string'
str[:-1]

'this is a strin'

In [1]:
print(not 4 == 'Data')

True


In [2]:
team = [
    ('Martha', 20, 'center'),
    ('Ana', 22, 'point guard'),
    ('Gabi', 22, 'Shooting guard'),
    ('Luz', 21, 'Power Forward'),
    ('Lorena', 19, 'Small Forward')
]

In [19]:
def player_position(players):
    result = []
    for name, age, position in players:
        result.append('Name: {:>19} \nPosition: {:>15}\n'.format(name, position))
    return result

In [20]:
for player in player_position(team):
    print(player)

Name:              Martha 
Position:          center

Name:                 Ana 
Position:     point guard

Name:                Gabi 
Position:  Shooting guard

Name:                 Luz 
Position:   Power Forward

Name:              Lorena 
Position:   Small Forward



In [21]:
for left in range(7):
    for right in range(left, 7):
        print(f'{left}|{right}', end=" ")
    print('\n')

0|0 0|1 0|2 0|3 0|4 0|5 0|6 

1|1 1|2 1|3 1|4 1|5 1|6 

2|2 2|3 2|4 2|5 2|6 

3|3 3|4 3|5 3|6 

4|4 4|5 4|6 

5|5 5|6 

6|6 



In [22]:
dominos = []
for left in range(7):
    for right in range(left, 7):
        dominos.append((left, right))
dominos

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 5),
 (5, 6),
 (6, 6)]

In [27]:
dominos[0]

(0, 0)

In [28]:
pips_from_loop = []
for domino in dominos:
        pips_from_loop.append(domino[0] + domino[1])
print(pips_from_loop)

[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7, 8, 6, 7, 8, 9, 8, 9, 10, 10, 11, 12]


In [29]:
pips_from_comp = [domino[0] + domino[1] for domino in dominos]
print(pips_from_comp)
print()
print(pips_from_comp == pips_from_loop)

[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7, 8, 6, 7, 8, 9, 8, 9, 10, 10, 11, 12]

True


In [1]:
import pandas as pd

In [5]:
data = {'student_id': [1,2,3,4], 'age': [15,11,11,20]}
df = pd.DataFrame(data)
df

student_id  age
0           1   15
1           2   11
2           3   11
3           4   20

In [9]:
[df.shape[0], df.shape[1]]

[4, 2]